### ISSUE TITLE
Error: Cannot find module './providers/address'

### ISSUE THREAD

**Issue by andre-dw** [Akryum/meteor-vue-component#43]
`/Users/andre/.meteor/packages/meteor-tool/.1.3.4_1.1ff5caj++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
						throw(ex);
						      ^
Error: Cannot find module './providers/address'
    at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:85:1)
    at node_modules/casual/src/casual.js:44:1
    at Array.forEach (/Users/andre/.meteor/packages/es5-shim/.4.5.12_1.1lhrgdi++os+web.browser+web.cordova/npm/node_modules/es5-shim/es5-shim.js:435:21)
    at Object.<anonymous> (node_modules/casual/src/casual.js:42:1)
    at meteorInstall.node_modules.casual.src.casual.js (node_modules/casual/src/casual.js:70:1)
    at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)
    at Module.require (packages/modules-runtime/.npm/package/node_modules/install/install.js:82:1)
    at Module.Mp.import (/Users/andre/.meteor/packages/modules/.0.6.4.a3rtmj++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:70:16)
    at meteorInstall.imports.api.apollo.resolvers.js (/Users/andre/IdeaRevolution/meteor_webpack/.meteor/local/build/programs/server/app/app.js:30:25)
    at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)
Exited with code: 8
Your application is crashing. Waiting for file change.`

**Comment by Akryum** [comment]
I need more details.
For example, what are the contents of the `.meteor/packages` and `.meteor/versions` files in your project?
