### ISSUE TITLE
App crashing: Vue Router

### ISSUE THREAD

**Issue by janat08** [Akryum/meteor-vue-component#47]
Did npm install which resulted in: (which is weird)
```
C:\Users\ALERATOR\garlic>meteor npm install
[..................] / normalizeTree: sill install loadCurrentTree
[..................] / normalizeTree: sill install loadCurrentTree
[..................] / normalizeTree: sill install loadCurrentTree
[..................] / normalizeTree: sill install loadCurrentTree
[..................] / normalizeTree: sill install loadCurrentTree
[..................] / normalizeTree: sill install loadCurrentTree
[   ...............] - cloneCurrentTree: sill cloneCurrentTree Finishing
[        ..........] / loadDevDeps: sill install loadAllDepsIntoIdealTree
[             .....] \ fetch: sill doParallel fetch 0
```

Looking at the example project for vue-router it doesn't import vue anywere.
Than:
```
Your app is crashing. Here's the latest log:
Errors prevented startup:

While processing files with akryum:vue-router (for target web.browser):
C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-router\0.2.0\plugin.vue-router.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\node_modules\babylon\lib\parser\location.js:22:13: Unexpected token (49:1)

  at Parser.pp.raise (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-router\0.2.0\plugin.vue-router.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\node_modules\babylon\lib\parser\location.js:22:13)

  at Parser.pp.unexpected (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-router\0.2.0\plugin.vue-router.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\node_modules\babylon\lib\parser\util.js:89:8)

  at Parser.pp.expect (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-router\0.2.0\plugin.vue-router.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\node_modules\babylon\lib\parser\util.js:83:33)
  at Parser.pp.parseObj (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-router\0.2.0\plugin.vue-router.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\node_modules\babylon\lib\parser\expression.js:725:12)
  at Parser.pp.parseExprAtom (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-router\0.2.0\plugin.vue-router.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\node_modules\babylon\lib\parser\expression.js:486:19)
  at Parser.parseExprAtom (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-router\0.2.0\plugin.vue-router.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\node_modules\babylon\lib\plugins\jsx\index.js:18:22)
  at Parser.pp.parseExprSubscripts (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-router\0.2.0\plugin.vue-router.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\node_modules\babylon\lib\parser\expression.js:272:19)
  at Parser.pp.parseMaybeUnary (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-router\0.2.0\plugin.vue-router.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\node_modules\babylon\lib\parser\expression.js:252:19)
  at Parser.pp.parseExprOps (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-router\0.2.0\plugin.vue-router.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\node_modules\babylon\lib\parser\expression.js:183:19)
  at Parser.pp.parseMaybeConditional (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-router\0.2.0\plugin.vue-router.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\node_modules\babylon\lib\parser\expression.js:165:19)
  at Parser.pp.parseMaybeAssign (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-router\0.2.0\plugin.vue-router.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\node_modules\babylon\lib\parser\expression.js:128:19)
  at Parser.pp.parseExpression (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-router\0.2.0\plugin.vue-router.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\node_modules\babylon\lib\parser\expression.js:92:19)
  at Parser.pp.parseReturnStatement (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-router\0.2.0\plugin.vue-router.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\node_modules\babylon\lib\parser\statement.js:333:26)
  at Parser.pp.parseStatement (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-router\0.2.0\plugin.vue-router.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\node_modules\babylon\lib\parser\statement.js:107:19)
  at Parser.parseStatement (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-router\0.2.0\plugin.vue-router.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\node_modules\babylon\lib\plugins\flow.js:30:22)
  at Parser.pp.parseBlockBody (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-router\0.2.0\plugin.vue-router.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\node_modules\babylon\lib\parser\statement.js:529:21)
  at Parser.pp.parseBlock (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-router\0.2.0\plugin.vue-router.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\node_modules\babylon\lib\parser\statement.js:510:8)
  at Parser.pp.parseFunctionBody (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-router\0.2.0\plugin.vue-router.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\node_modules\babylon\lib\parser\expression.js:913:22)
  at Parser.parseFunctionBody (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-router\0.2.0\plugin.vue-router.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\node_modules\babylon\lib\plugins\flow.js:17:20)
  at Parser.pp.parseArrowExpression (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-router\0.2.0\plugin.vue-router.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\node_modules\babylon\lib\parser\expression.js:892:8)
  at Parser.parseParenAndDistinguishExpression (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-router\0.2.0\plugin.vue-router.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\node_modules\babylon\lib\plugins\flow.js:396:21)
  at Parser.pp.parseExprAtom (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-router\0.2.0\plugin.vue-router.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\node_modules\babylon\lib\parser\expression.js:476:19)
  at Parser.parseExprAtom (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-router\0.2.0\plugin.vue-router.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\node_modules\babylon\lib\plugins\jsx\index.js:18:22)
  at Parser.pp.parseExprSubscripts (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-router\0.2.0\plugin.vue-router.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\node_modules\babylon\lib\parser\expression.js:272:19)
  at Parser.pp.parseMaybeUnary (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-router\0.2.0\plugin.vue-router.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\node_modules\babylon\lib\parser\expression.js:252:19)
  at Parser.pp.parseExprOps (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-router\0.2.0\plugin.vue-router.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\node_modules\babylon\lib\parser\expression.js:183:19)
  at Parser.pp.parseMaybeConditional (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-router\0.2.0\plugin.vue-router.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\node_modules\babylon\lib\parser\expression.js:165:19)
  at Parser.pp.parseMaybeAssign (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-router\0.2.0\plugin.vue-router.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\node_modules\babylon\lib\parser\expression.js:128:19)
  at Parser.pp.parseParenAndDistinguishExpression (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-router\0.2.0\plugin.vue-router.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\node_modules\babylon\lib\parser\expression.js:590:26)
  at Parser.parseParenAndDistinguishExpression (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-router\0.2.0\plugin.vue-router.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\node_modules\babylon\lib\plugins\flow.js:399:28)
  at Parser.pp.parseExprAtom (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-router\0.2.0\plugin.vue-router.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\node_modules\babylon\lib\parser\expression.js:476:19)
  at Parser.parseExprAtom (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-router\0.2.0\plugin.vue-router.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\node_modules\babylon\lib\plugins\jsx\index.js:18:22)
  at Parser.pp.parseExprSubscripts (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-router\0.2.0\plugin.vue-router.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\node_modules\babylon\lib\parser\expression.js:272:19)
  at Parser.pp.parseMaybeUnary (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-router\0.2.0\plugin.vue-router.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\node_modules\babylon\lib\parser\expression.js:252:19)
  at Parser.pp.parseExprOps (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-router\0.2.0\plugin.vue-router.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\node_modules\babylon\lib\parser\expression.js:183:19)
  at Parser.pp.parseMaybeConditional (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-router\0.2.0\plugin.vue-router.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\node_modules\babylon\lib\parser\expression.js:165:19)
  at Parser.pp.parseMaybeAssign (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-router\0.2.0\plugin.vue-router.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\node_modules\babylon\lib\parser\expression.js:128:19)
  at Parser.pp.parseVar (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-router\0.2.0\plugin.vue-router.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\node_modules\babylon\lib\parser\statement.js:601:24)
  at Parser.pp.parseVarStatement (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-router\0.2.0\plugin.vue-router.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\node_modules\babylon\lib\parser\statement.js:424:8)
  at Parser.pp.parseStatement (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-router\0.2.0\plugin.vue-router.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\node_modules\babylon\lib\parser\statement.js:120:19)
  at Parser.parseStatement (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-router\0.2.0\plugin.vue-router.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\node_modules\babylon\lib\plugins\flow.js:30:22)
  at Parser.pp.parseBlockBody (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-router\0.2.0\plugin.vue-router.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\node_modules\babylon\lib\parser\statement.js:529:21)
  at Parser.pp.parseTopLevel (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-router\0.2.0\plugin.vue-router.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\node_modules\babylon\lib\parser\statement.js:36:8)
  at Parser.parse (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-router\0.2.0\plugin.vue-router.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\node_modules\babylon\lib\parser\index.js:129:19)
  at Object.parse (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-router\0.2.0\plugin.vue-router.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\node_modules\babylon\lib\index.js:47:47)
  at parse (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-router\0.2.0\plugin.vue-router.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\index.js:38:29)
  at C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-router\0.2.0\plugin.vue-router.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\index.js:58:15
  at Cache.Cp.get (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-router\0.2.0\plugin.vue-router.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\cache.js:94:19)
  at Object.compile (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-router\0.2.0\plugin.vue-router.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\index.js:47:23)
  at Object.Babel.compile (packages/babel-compiler/babel.js:26:1)
  at VueRouterCompiler.compileOneFile (packages/vue-router/plugin/plugin.js:44:24)
  at packages/caching-compiler/caching-compiler.js:292:32
  at C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-router\0.2.0\plugin.vue-router.os\npm\node_modules\meteor\caching-compiler\node_modules\async\lib\async.js:182:20
  at replenish (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-router\0.2.0\plugin.vue-router.os\npm\node_modules\meteor\caching-compiler\node_modules\async\lib\async.js:317:21)
  at C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-router\0.2.0\plugin.vue-router.os\npm\node_modules\meteor\caching-compiler\node_modules\async\lib\async.js:328:15
  at Object.async.forEachLimit.async.eachLimit (C:\Users\ALERATOR\AppData\Local\.meteor\packages\akryum_vue-router\0.2.0\plugin.vue-router.os\npm\node_modules\meteor\caching-compiler\node_modules\async\lib\async.js:221:35)
  at VueRouterCompiler.processFilesForTarget (packages/caching-compiler/caching-compiler.js:277:11)


Your application has errors. Waiting for file change.
```

**Comment by Akryum** [comment]
> Looking at the example project for vue-router it doesn't import vue anywere.

Vue is used internally by `vue-router`.

> Unexpected token (49:1)

What is the content of your route files (`.routes.js`)?

**Comment by janat08** [comment]
I've found the error at 49:1.

**Comment by Akryum** [comment]
Can I close this issue?

**Comment by janat08** [comment]
yes thankyou, but consider changing error logs although it must be self-evident where to look at.
