### ISSUE TITLE
Subscribes error

### ISSUE THREAD

**Issue by inssitu** [Akryum/meteor-vue-component#55]
Hi, I have found an error, when I subscribe to Tracks and I go to /tracks first time is working, but if I navigate to others links and I come back to /tracks page I get this error:

Error
```
I20160730-12:27:45.013(2)? Exception from sub lastsTracks id 3wiCxcog9XjgppMb5 Error: Match error: Failed M
atch.OneOf, Match.Maybe or Match.Optional validation
I20160730-12:27:45.013(2)?     at exports.check (packages/check/match.js:34:1)
I20160730-12:27:45.013(2)?     at [object Object]._getFindOptions (packages/mongo/collection.js:277:7)
I20160730-12:27:45.013(2)?     at [object Object].find (packages/mongo/collection.js:316:39)
I20160730-12:27:45.013(2)?     at [object Object].Tracks.lastsTracks (lib/collections/tracks.js:4:16)
I20160730-12:27:45.013(2)?     at Subscription._handler (server/publications/tracks.js:2:16)
I20160730-12:27:45.013(2)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1704:12)
I20160730-12:27:45.014(2)?     at Subscription._runHandler (packages/ddp-server/livedata_server.js:1026:17)
I20160730-12:27:45.014(2)?     at Session._startSubscription (packages/ddp-server/livedata_server.js:845:9)
I20160730-12:27:45.014(2)?     at Session.sub (packages/ddp-server/livedata_server.js:617:12)
I20160730-12:27:45.014(2)?     at packages/ddp-server/livedata_server.js:551:43
I20160730-12:27:45.016(2)? Sanitized and reported to the client as: Match failed [400]
I20160730-12:27:45.016(2)?
```

lib/collections/tracks.js
```
Tracks = new Mongo.Collection('tracks');

Tracks.lastsTracks = function(limit) {
	return Tracks.find(
    {$or: [{status: 'published'}, {status: 'sold'}]},
    {sort: {publishedAt: -1}, limit: limit}
	);
};
```

server/publications/tracks.js
```
Meteor.publish('lastsTracks', function(limit){
	return Tracks.lastsTracks(limit);
});
```

Tracks.vue
```
    meteor: {
      subscribe: {
        'lastsTracks': [50]
      },
      data: {
        tracks () {
          return Tracks.find();
        },
      }
    }
```

**Comment by inssitu** [comment]
There is no issue if I use the $subscribe method in the component code 

```
    ready(){
      this.$subscribe('lastsTracks', 50);
    }
```

**Comment by Akryum** [comment]
Please update to the latest akryum:vue package and it should be fixed.
