### ISSUE TITLE
Error updating to 1.4.0.1

### ISSUE THREAD

**Issue by inssitu** [Akryum/meteor-vue-component#61]
/Users/Salvatore/.meteor/packages/meteor-tool/.1.4.0-1.cbcnkw++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
						throw(ex);
						^

ReferenceError: FlowRouter is not defined
    at meteorInstall.lib.routes.js (lib/routes.js:1:1)
    at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)
    at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:82:1)
    at /Users/Salvatore/Code/gho/.meteor/local/build/programs/server/app/app.js:294:1
    at /Users/Salvatore/Code/gho/.meteor/local/build/programs/server/boot.js:297:10
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/Salvatore/.meteor/packages/meteor-tool/.1.4.0-1.cbcnkw++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
    at /Users/Salvatore/Code/gho/.meteor/local/build/programs/server/boot.js:133:5
Exited with code: 1
Your application is crashing. Waiting for file change.

**Comment by Akryum** [comment]
It seems FlowRouter is not installed.

**Comment by Akryum** [comment]
Did you try to delete then add back flowrouter? (I advise you to use [vue-router](https://github.com/Akryum/meteor-vue-component/tree/master/packages/vue-router#installation) instead, it's far better integrated with vue).

**Comment by inssitu** [comment]
Thanks @Akryum, it's working now with [vue-router](https://github.com/Akryum/meteor-vue-component/tree/master/packages/vue-router)

**Comment by Akryum** [comment]
Glad to hear it!
