### ISSUE TITLE
SASS lang problem

### ISSUE THREAD

**Issue by suezzo** [Akryum/meteor-vue-component#64]
Hello,
I'm trying to start project using Vue.js + Meteor, but when I was preparing my application I got problem with Sass compiling. When I use `<style lang="scss">` my Meteor console shows below errror

````  
While processing files with akryum:vue-component (for target
   web.browser):
   packages/vue-component/plugin/utils.js:132:13: [vue-component] Error
   while compiling in tag <style> using lang scss
   at throwCompileError (packages/vue-component/plugin/utils.js:132:13)
   at VueComponentTagHandler.getResults
   (packages/vue-component/plugin/tag-handler.js:246:11)
   at compileTags
   (packages/vue-component/plugin/vue-compiler.js:519:18)
   at compileOneFileWithContents
   (packages/vue-component/plugin/vue-compiler.js:534:12)
   at VueCompo.compileOneFile
   (packages/vue-component/plugin/vue-compiler.js:128:12)
   at packages/vue-component/plugin/vue-compiler.js:49:34
   at
   C:\Users\Michal\AppData\Local\.meteor\packages\akryum_vue-component\0.6.6\plugin.vue-component.os\npm\node_modules\meteor\vue-component\node_modules\async\lib\async.js:182:20
   at replenish
   (C:\Users\Michal\AppData\Local\.meteor\packages\akryum_vue-component\0.6.6\plugin.vue-component.os\npm\node_modules\meteor\vue-component\node_modules\async\lib\async.js:317:21)
   at
   C:\Users\Michal\AppData\Local\.meteor\packages\akryum_vue-component\0.6.6\plugin.vue-component.os\npm\node_modules\meteor\vue-component\node_modules\async\lib\async.js:324:29
   at
   C:\Users\Michal\AppData\Local\.meteor\packages\akryum_vue-component\0.6.6\plugin.vue-component.os\npm\node_modules\meteor\vue-component\node_modules\async\lib\async.js:44:16
   at packages/vue-component/plugin/vue-compiler.js:66:11
   at
   C:\Users\Michal\AppData\Local\.meteor\packages\akryum_vue-component\0.6.6\plugin.vue-component.os\npm\node_modules\meteor\vue-component\node_modules\async\lib\async.js:182:20
   at replenish
   (C:\Users\Michal\AppData\Local\.meteor\packages\akryum_vue-component\0.6.6\plugin.vue-component.os\npm\node_modules\meteor\vue-component\node_modules\async\lib\async.js:317:21)
   at
   C:\Users\Michal\AppData\Local\.meteor\packages\akryum_vue-component\0.6.6\plugin.vue-component.os\npm\node_modules\meteor\vue-component\node_modules\async\lib\async.js:328:15
   at Object.async.forEachLimit.async.eachLimit
   (C:\Users\Michal\AppData\Local\.meteor\packages\akryum_vue-component\0.6.6\plugin.vue-component.os\npm\node_modules\meteor\vue-component\node_modules\async\lib\async.js:221:35)
   at VueCompo.processFilesForTarget
   (packages/vue-component/plugin/vue-compiler.js:33:11)
````

Do you have any advice how can I fix this issue?

**Comment by Akryum** [comment]
What is the full content of your console?

**Comment by suezzo** [comment]
Sorry I missed the rest of the console log.

````
=> Client modified -- refreshing (x6)[vue-component] Error while compiling in tag <style> using lang scss -> in imports/ui/HomePage.vue at line 17
[ReferenceError: tag is not defined]
[TypeError: Cannot read property 'styles' of null]
[vue-component] Error while compiling in tag <style> using lang scss -> in imports/ui/HomePage.vue
[ReferenceError: tag is not defined]

=> Errors prevented startup:

   While processing files with akryum:vue-component (for target
   web.browser):
   packages/vue-component/plugin/utils.js:132:13: [vue-component] Error
   while compiling in tag <style> using lang scss
   at throwCompileError (packages/vue-component/plugin/utils.js:132:13)
   at VueComponentTagHandler.getResults
   (packages/vue-component/plugin/tag-handler.js:246:11)
   at compileTags
   (packages/vue-component/plugin/vue-compiler.js:519:18)
   at compileOneFileWithContents
   (packages/vue-component/plugin/vue-compiler.js:534:12)
   at VueCompo.compileOneFile
   (packages/vue-component/plugin/vue-compiler.js:128:12)
   at packages/vue-component/plugin/vue-compiler.js:49:34
   at
   C:\Users\Michal\AppData\Local\.meteor\packages\akryum_vue-component\0.6.6\plugin.vue-component.os\npm\node_modules\meteor\vue-component\node_modules\async\lib\async.js:182:20
   at replenish
   (C:\Users\Michal\AppData\Local\.meteor\packages\akryum_vue-component\0.6.6\plugin.vue-component.os\npm\node_modules\meteor\vue-component\node_modules\async\lib\async.js:317:21)
   at
   C:\Users\Michal\AppData\Local\.meteor\packages\akryum_vue-component\0.6.6\plugin.vue-component.os\npm\node_modules\meteor\vue-component\node_modules\async\lib\async.js:324:29
   at
   C:\Users\Michal\AppData\Local\.meteor\packages\akryum_vue-component\0.6.6\plugin.vue-component.os\npm\node_modules\meteor\vue-component\node_modules\async\lib\async.js:44:16
   at packages/vue-component/plugin/vue-compiler.js:66:11
   at
   C:\Users\Michal\AppData\Local\.meteor\packages\akryum_vue-component\0.6.6\plugin.vue-component.os\npm\node_modules\meteor\vue-component\node_modules\async\lib\async.js:182:20
   at replenish
   (C:\Users\Michal\AppData\Local\.meteor\packages\akryum_vue-component\0.6.6\plugin.vue-component.os\npm\node_modules\meteor\vue-component\node_modules\async\lib\async.js:317:21)
   at
   C:\Users\Michal\AppData\Local\.meteor\packages\akryum_vue-component\0.6.6\plugin.vue-component.os\npm\node_modules\meteor\vue-component\node_modules\async\lib\async.js:328:15
   at Object.async.forEachLimit.async.eachLimit
   (C:\Users\Michal\AppData\Local\.meteor\packages\akryum_vue-component\0.6.6\plugin.vue-component.os\npm\node_modules\meteor\vue-component\node_modules\async\lib\async.js:221:35)
   at VueCompo.processFilesForTarget
   (packages/vue-component/plugin/vue-compiler.js:33:11)
````

**Comment by Akryum** [comment]
What is the content of your `<style>` tag?

**Comment by suezzo** [comment]
I think that I found the problem. It's the `akryum:vue-sass` package. When I type command `meteor add akryum:vue-sass` I'm getting below error.

````
 => Errors while adding packages:

While checking for akryum:vue-sass@0.0.4:
error: No compatible binary build found for this package. Contact the
package author and ask them to publish it for your platform.
````

I face this type of error for the first time. Do you have any idea how to fix it?

**Comment by Akryum** [comment]
Which version of meteor are your using?

**Comment by suezzo** [comment]
Meteor 1.4.1.1

**Comment by Akryum** [comment]
https://github.com/Akryum/meteor-vue-component/tree/master/packages/vue-sass

@benjamn Shouldn't Meteor rebuild binaries in Atmosphere packages when installing them?

**Comment by bduff9** [comment]
Any word on this?  I am also running into the same error as @suezzo when trying to install vue-sass.

**Comment by Akryum** [comment]
On which os are you?
Could you execute this command?

```
meteor publish-for-arch akryum:vue-sas@0.0.4
```

**Comment by bduff9** [comment]
@Akryum thanks for your reply.  I was working on a linux distro of Kali, but to check if that was the issue I just tried to install on m work laptop, which is windows.  That did work so I then went back to Kali and now that works as well.  Not sure what has changed but for now I think I'm good.  Thanks again!

**Comment by Akryum** [comment]
Closing for now. Feel free to comment if anything goes wrong again!
